services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=webrtc-hub'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
